language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

cache:
  - npm
  - composer

env:
  global:
    - DEPLOY_DOCS=false
    - PHPDOC=2

matrix:
  fast_finish: false
  include:
    - php: 7.2
      env: PHPDOC=3
    - php: 7.2
      env: DEPLOY_DOCS=true

  allow_failures:
    - php: 7.2
      env: PHPDOC=3
    - php: 5.6
    - php: 7.0

before_install:
  # Update composer
  - composer self-update

  # Setup Git
  - git config --global user.email "deploy@travis-ci.org"
  - git config --global user.name "Travis CI Bot"

  # Setup Composer
  - composer global config minimum-stability dev
  - composer global config prefer-stable true
  - export PATH="$(composer config -g home)/vendor/bin:$PATH"

  # Use Nove v8
  - nvm use v8

  # Install/update Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - | # phpDocumentor 3-dev
    if [[ $PHPDOC == '3' ]]; then
      composer global require phpdocumentor/phpdocumentor:dev-develop
      composer global require symfony/dotenv
    fi

  - composer install --no-interaction
  - npm install

script:
  - |
    if [[ $PHPDOC == '3' ]]; then
      phpdoc -d demo/ -t docs/demo/ --force --template=data/templates/vuepress/
    else
      composer build:api
    fi

  - npm run docs:build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/phpdoc-vuepress
  project-name: "nelson6e65/phpdoc-vuepress [${TRAVIS_COMMIT_RANGE}]"
  on:
    branch: master
    condition: $DEPLOY_DOCS = true
  verbose: true
